### PR TITLE
fix: export component props in dist

### LINKED ISSUE #676: Export Component Prop Types for Extensibility
**Issue**

Current, not all component props definitions are exported for use by applications incorporating this package. For example, the type for `KMLDataSourceProps` is not exported in a way that makes it available for extension by another component.  Attempting to use the definition results in the following error:

image

Attempting to import the definition results in this error:

image

**Proposed Solution**

Export type definitions so that they can be used by applications incorporating this library.

**Implementation**

Is there any guidance for submitting an PR to resolve this issue.  I'm willing to create and submit one myself; however, I'd like to know of any guidance or potential pitfalls related to this issue.

### PR DESCRIPTION
**Pull request by reggie3-braingu**
- updates individual component `index .ts` files to export component prop types
- updates the root `index.ts` file to export components prop types

fixes #676 

## Summary by CodeRabbit

- **New Features**
	- Enhanced module interfaces by adding type exports for various components, improving clarity and usability in TypeScript.
  
- **Documentation**
	- Updated export statements to include associated type definitions for better understanding and integration.

### CODE REVIEW

**Comment by keiya01** [comment]
@reggie3-braingu Thanks for your PR. I reviewed your PR. It looks good to me.
There are some comments from coderabbitai. Have these comments been resolved?

**Comment by reggie3-braingu** [comment]
Hi @keiya01 , thank you for taking a look at this PR.  I'm confused by what the coderabbitai bot is saying here.  It's saying that almost all of the files do not export the component prop, but the props are being exported (as far as I can tell).  Are you able to explain what the bot is trying to get me to do?

**Review by keiya01 — APPROVED** [review]
Understood. It looks these suggestions are weird, so we wouldn't need to handle it.
Thank you @reggie3-braingu .

**Comment by arngc** [comment]
Please confirm, does this commit also resolve this issue? https://github.com/reearth/resium/issues/675

**Comment by reggie3-braingu** [comment]
@arngc , it doesn't. My PR just exports the component props.

**Pull request merged**
