### PR TITLE
fix: terrain isn't loaded

### PR DESCRIPTION
**Pull request by keiya01**

### CODE REVIEW

**Comment by Primajin** [comment]
Hey there @keiya01 - I seem to have the opposite problem: Since this change in `1.18.1` my terrain isn't loaded anymore - with `1.18.0` it still works.

**Comment by MatthewHerbst** [comment]
Seeing a similar issue to @Primajin where when we change the value of the `terrainProvider` passed to `Viewer` when switching between various terrain tilesets, Cesium does not update to reflect that change.

Should `terrainProvider` be included in the `cesiumProps` category in https://github.com/reearth/resium/blob/9c95c87859593ca76d8af981720034249aa37815/src/Viewer/Viewer.ts#L41 instead of in `otherProps`?

**Comment by keiya01** [comment]
@Primajin Thank you. I investigated the issue, but I couldn't see it.
Is [this story](https://github.com/reearth/resium/pull/670/files#diff-5103611a3d8e49ea9ebf85552f3cf17965f5061a742aad641afce3a0e6d727aaR37-R44) your issue? This story toggles EllipsoidTerrainProvider and CesiumTerrainProvider. But this is still working in 1.18.1.
Could you give me a more specific code if possible?

**Comment by MatthewHerbst** [comment]
For us, we're swapping a `TerrainRgbProvider` with a new `TerrainRgbProvider`.
We've resolved the issue in our code by forcing a terrain provider update when we toggle between providers:

```tsx
// We load this hook in our `Viewer` component wrapper
export function useUpdateTerrainProvider(
    viewerRef: MutableRefObject<CesiumComponentRef<Viewer> | null>,
    terrainProvider: TerrainProvider,
) {
    useEffect(() => {
        if (!viewerRef.current?.cesiumElement) {
            return;
        }

        viewerRef.current.cesiumElement.terrainProvider = terrainProvider;
    }, [terrainProvider, viewerRef]);
}
```

**Comment by keiya01** [comment]
@MatthewHerbst Thanks for your help. I fixed it in [v1.18.2](https://github.com/reearth/resium/releases/tag/v1.18.2). Could you try it?

**Comment by Primajin** [comment]
Sorry for not responding earlier @keiya01 , I can confirm that `1.18.2` works as expected again. Thanks a lot for the fix 🙏🏻

**Comment by Primajin** [comment]
There is also an odd quirk when using a VPN (which is obviously beyond control of this project) the terrain doesn't load for me - when I deactivate it it works fine.

**Comment by MatthewHerbst** [comment]
Apologies for the delayed response. 1.18.2 has not resolved the issue for us. From a React perspective, I would expect the changing the `terrainProvider` prop provided to `Viewer` to completely re-render the component. At it's most simple this could simply be destroy the Cesium instance and re-create it. More complex would be manually changing the `cesiumElement.terrainProvider` as I do in the hook I made to resolve this. I realize Cesium is a bit more nuanced about what a re-render actually means, but I don't think anything fancy needs to happen here. Happy to share anything that would be useful.

**Pull request merged**
